defaults: &defaults
  adapter: postgresql
  host: localhost
  encoding: unicode
  pool: 5

development:
  <<: *defaults
  database: resume_dev

test: &test
  <<: *defaults
  database: resume_test

production:
  <<: *defaults
  host: <%= ENV["PG_HOST"] %>
  database: <%= ENV["PG_DATABASE"] %>
  username: <%= ENV["PG_USERNAME"] %>
  password: <%= ENV["PG_PASSWORD"] %>

cucumber:
  <<: *test
